version: '3.8'

services:
  bot:
    build: .
    container_name: codedojo_bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Jakarta
